spring:
  application:
    name: todo
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
  config:
    import: optional:file:.env[.properties]

groq:
  api-key: ${GROQ_API_KEY}
  model: llama-3.1-8b-instant
  system-prompt-path: classpath:prompts/system-prompt.txt